# Dependabot will run on day 14 of each month at 03:59 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "59 3 14 * *"
    open-pull-requests-limit: 15
  - package-ecosystem: "npm"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "59 3 14 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"
    directories: "**/*"
