os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:chris-lea/redis-server -y; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install redis-server redis-sentinel -y; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo systemctl start redis-server; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install redis; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist; sleep 10; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install redis-64; powershell "Start-Process redis-server.exe -PassThru"; sleep 10; fi'
  - sleep 15
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chmod ogu+x test/redis-socket/setup-socket.sh; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chmod ogu+x test/redis-sentinel/*.sh; fi'
script:
  - 'npm run tsc || true'
  - 'npm test && if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test/redis-socket/setup-socket.sh && cd test/redis-sentinel && ./test-sentinel.sh && cd ../..; fi'
after_success:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm install -g npm@latest; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm install --package-lock-only --production; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm audit; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm ls; fi'
env:
  - CXX=g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
